### ISSUE TITLE
Undefined field isa_closure

### ISSUE THREAD

**Issue by tmushayahama** [berkeleybop/bbop-manager-golr#9]
@kltm I dont know if this is an amigo issue (it works outside manager builder). 

Adding a query filter of isa_closure gives an undefined field error

Using `manager.add_query_filter('isa_closure', 'CHEBI:33695');`

There is a closure called isa_partof_closure, is that the same?

![image](https://user-images.githubusercontent.com/2273929/38290681-4acac5d6-3791-11e8-8b90-8cbb29d3cb89.png)

And the query string parameters

![image](https://user-images.githubusercontent.com/2273929/38291074-ed035ec0-3792-11e8-944f-331097674c5d.png)

**Comment by kltm** [comment]
Until there is a public index that includes the `isa_closure`, pinning to that field will not work.

**Comment by kltm** [comment]
To clarify that a bit more, the code is already in place for this in AmiGO 2.5, but that needs to be released and have it's indices built for it, which is pending the transfer of the AmiGO production site from Stanford to Berkeley. There is no code or process change that can happen in the code base in this abstract library's repo.
